# Generated by Django 4.0.6 on 2022-07-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sei', models.CharField(db_column='姓', max_length=32)),
            ],
            options={
                'db_table': '世帯',
            },
        ),
        migrations.CreateModel(
            name='Staiin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mei', models.CharField(db_column='名前', max_length=32)),
                ('setai', models.ForeignKey(db_column='世帯ID', on_delete=django.db.models.deletion.PROTECT, to='dummy_app.setai')),
            ],
            options={
                'db_table': '世帯員',
            },
        ),
    ]
