# Generated by Django 4.0.6 on 2022-07-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staiin',
            new_name='Setaiin',
        ),
    ]
